mysql:
  secrets:
    MYSQL_ROOT_PASSWORD: changeme
    MYSQL_USER: changeme
    MYSQL_PASSWORD: changeme

todoapp:
  namespace: todoapp
  image:
    repository: changeme
    tag: changeme

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  secrets:
    SECRET_KEY: changeme
    DB_NAME: changeme
    DB_USER: changeme
    DB_PASSWORD: changeme
    DB_HOST: changeme

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      avarageUtilization: 70
    memory:
      avarageUtilization: 70

  volumes:
    persistentVolume:
      capacity: "1Gi"
    persistentVolumeClaim:
      requestStorage: "1Gi"